### ISSUE TITLE
1.5.5 undefined symbol

### ISSUE THREAD

**Issue by sannacho** [Helltar/gcencryptor#1]
Ubuntu 22.04 base problems to run 1.5.5 version:
_symbol lookup error: gcencryptor: undefined symbol: QGuiApplication_setFallbackSessionManagementEnabled_

1.5.4 version no problem

Lazarus version problem?

Regards...

**Comment by Helltar** [comment]
Hmm, indeed, in the Ubuntu 22 repositories is a different version of the **libqt5pas1** library.

You can remove it and install from here:

https://github.com/davidbannon/libqt5pas
https://github.com/davidbannon/libqt5pas/releases/tag/v1.2.15 (**libqt5pas1_2.15-1_amd64.deb**)

In the near future, I will try to rebuild with the version of **libqt5pas1** that is provided in Ubuntu 22.04, if no issues arise with it.

**Comment by sannacho** [comment]
it works. thank you so much. We will be attentive to the new build to avoid upgrade the base libraries as much as possible

**Comment by Helltar** [comment]
Done. Please check: https://github.com/Helltar/gcencryptor/releases/tag/1.5.6

**Comment by sannacho** [comment]
Yesss, Done...Good Job!

Thank you very much
